spring:
  data:
    mongodb:
      authentication-database: admin
      database: springbootdemotest
      host: localhost
      password: example
      port: 27017
      repositories:
        type: auto
      username: root
